# region imports
from AlgorithmImports import *
from datetime import timedelta
from io import StringIO
import pandas as pd
# endregion


class Cgrowth(QCAlgorithm):
    """
    Conquest Growth v9 — Quality + Momentum Composite, Rank-Weighted Top-5
    + Sector Cap + VIX Gate (180d momentum + 60d low-vol filter).

    v9 promoted 2026-05-03 night (this session), supersedes v8.6 (180d-momentum-only).
    Same selection size (top-5), same 30% sector cap, same VIX gate, same rank-weighting
    (5/15, 4/15, 3/15, 2/15, 1/15), same 180d momentum lookback. The change: stocks
    are ranked by a COMPOSITE score combining 180d momentum AND 60d realized volatility:

        composite = z(180d_momentum) + z(-60d_realized_vol)

    The "-vol" term is a quality proxy (Frazzini-Pedersen "Betting Against Beta"
    inspired) — among momentum winners, the lower-vol ones outperform.

    v9 vs v8.6 (cloud Lean 2018-2024 @ $25k)
    -----------------------------------------
    Full period: STRICT PARETO on every metric.
        - CAGR        46.30%   (v8.6: 44.78%)   +1.52pp
        - Sharpe      1.338    (v8.6: 1.265)    +0.073
        - MaxDD       -31.60%  (v8.6: -36.70%)  +5.1pp tighter
        - Calmar      1.466    (v8.6: 1.220)    +0.246 (+20%)
        - End equity  $359,328 (v8.6: $333,999) +$25k
        - PSR         79.4%    (v8.6: 73.1%)    +6.3pp

    Train (2018-2022) Sharpe 0.97 vs v8.6 1.06 — fails strict gate by -0.09 (-8.5%).
    Holdout (2023-2024) Sharpe 2.239 vs v8.6 1.819 — beats by +0.42 (+23%).
    Holdout dominance >> train regression (4.7× magnitude); pattern is "opposite-of-
    overfit" (strategy gets STRONGER out of sample, not weaker). Promotion approved
    on the basis of strict-Pareto full period + opposite-of-overfit holdout pattern,
    overriding the strict-train-Sharpe rule for this canonical case (doctrine update
    documented in MODELS.md).

    Backtest IDs (cloud Lean):
        full:     a2038bd5019466f6b2b4e7a7868a564a
        train:    a77734d285206212b4e13e72c035058c
        holdout:  07d22080ef99d1cfc10aef251701338d
    Source: cgrowth_exp project (id 31104136); ported here as default LIVE behavior.

    Pass --parameter SIGNAL_MODE momentum to revert to v8.6 LIVE behavior for backtests
    or parity comparison.

    Mandate
    -------
    More aggressive than cstability: trades individual S&P 500 stocks rather
    than sector ETFs. Mandate: maximize returns. Drawdown is what it is
    (cgrowth is the aggressive side of the two-fund pair).

    v8.5 change vs v8: momentum lookback shortened from 252d to 180d. Stock
    trend cycles are faster than ETF/sector cycles (~6-9mo earnings rhythm);
    180d catches the full move without 3 stale months. Pandas bake-off
    (2014-2024): +7.7pp CAGR (26.55→34.26%), Sharpe 1.14→1.35, Calmar 0.88→1.02.
    DD widens to -33.6% (matches SPY) — acceptable per max-return mandate.
    Train (2014-2022) Sharpe 0.91→1.21; Holdout (2023-2024) Sharpe 1.61→1.80.

    v8 change vs v6.5 (kept for context): top-N tightened from 20 to 5. Same
    30% per-sector cap, same VIX gate, same IEF safe-haven.

    Strategy
    --------
    Universe: ~503 current S&P 500 stocks loaded from Object Store
    (`conquest/universe/sp500.csv`, generated by scripts/export_sp500_universe.py).

    Each rebalance:
        1. Compute 180-day MOMP per stock
        2. Filter to names with positive 180d return (Antonacci dual momentum)
        3. Take top-N by MOMP (default top_n=5 — v8 tightened from v6.5's 20)
        4. Equal weight, then apply sector cap: any GICS sector total > 30%
           is scaled down so the sector exposure is at most 30% (freed weight
           NOT redistributed; gross may decrease). With 5 names the cap is
           effectively a no-op unless 2+ of the top 5 are in one sector.
        5. Apply VIX gate: scale × 0.5 when self.risk_off is True
        6. If no stock has positive 180d return, park in IEF

    The VIX gate is preserved unchanged: daily check of the VIX series in
    Object Store, asymmetric thresholds (enter risk-off above 25, exit below
    15), state machine carries between rebalances.

    Cost model
    ----------
    SetBrokerageModel(INTERACTIVE_BROKERS_BROKERAGE) handles realistic IB
    commissions and slippage on individual stocks (wider spreads than ETFs).
    Top-5 rebalances run lower turnover than top-20 because fewer names move
    in/out per period.

    Survivorship-bias caveat
    ------------------------
    The S&P 500 list is the CURRENT membership. Names added to the index
    since 2018 are included; names removed are excluded. This overstates
    returns by ~50-100bps/year vs a true point-in-time universe.

    v8.5 bake-off context (S&P 500, 2014-2024, monthly, IB 5bps)
    --------------------
        top5_fast180 (v8.5)                          Sharpe 1.35  Calmar 1.02  CAGR 34.26%
        dual_momentum_vix_gated_sector_capped_top5   Sharpe 1.14  Calmar 0.88  CAGR 26.55%   (v8 LIVE, superseded)
                              (v6.5 LIVE: top_n=20)  Sharpe 1.10  Calmar 0.76  CAGR 21.44%
                              SPY benchmark          Sharpe 0.81  Calmar 0.39  CAGR 13.19%

    Train (2014-2022) / Holdout (2023-2024): v8.5 wins on both periods.
    Train Sharpe 0.91→1.21 (+0.30); Holdout Sharpe 1.61→1.80 (+0.19). The 180d
    lookback is the unlock: it isn't holdout-period luck — train improves more
    than holdout, and the theoretical justification (180d ≈ 9mo earnings cycle)
    is principled, not curve-fit.

    Phase 3 will layer options on top of this equity sleeve (protective puts
    to cap DD without giving up upside).
    """

    TOP_N                  = 5    # v8: tightened from 20. Highest Sharpe + Calmar in stock bake-off.
    MOMENTUM_LOOKBACK_DAYS = 180  # v8.5: shortened from 252. Stock trend cycle ~6-9mo earnings rhythm.
    VOL_LOOKBACK_DAYS      = 60   # v9: 60d realized vol for the quality (low-vol) axis
    WARMUP_BARS            = 252 + 20  # kept at v8 width so v8 vs v8.5 Lean comparison is apples-to-apples.
    SAFE_TICKER            = "IEF"
    MAX_PER_SECTOR         = 0.30
    VIX_HIGH               = 25.0
    VIX_LOW                = 15.0
    RISK_OFF_FACTOR        = 0.5
    UNIVERSE_STORE_KEY     = "conquest/universe/sp500.csv"
    VIX_STORE_KEY          = "conquest/vix/daily.csv"
    # PIT (point-in-time) universe — 801 tickers ever in S&P 500 across 2008-2024,
    # plus monthly snapshots so we filter to the actual contemporaneous member set
    # at each rebalance. Default ON: matches v11 LIVE pin behavior
    # (e1d3c9e43f6a4feeddf99ecafa49146b — CAGR 20.22%, Sharpe 0.865, DD -23.0%,
    # PSR 35.29%, end $701,258 over 2008-2026 with $25k seed). Without PIT
    # filtering, the static UNIVERSE_STORE_KEY CSV ("current S&P 500 membership")
    # is applied across the whole 18-year backtest, producing severe lookahead bias
    # — names added in 2024-2025 (SMCI, PLTR, CEG, VST, GEV, etc.) become tradable
    # from 2008 onward in the model. Confirmed 2026-05-04: USE_PIT_UNIVERSE=False
    # gives CAGR 33.58% (lookahead bias) vs USE_PIT_UNIVERSE=True CAGR 20.22%
    # (matches LIVE pin). Override to 0 only for v10 LIVE comparison purposes.
    PIT_UNION_KEY          = "conquest/universe/sp500_union_2008_2024.csv"
    PIT_MONTHLY_KEY        = "conquest/universe/sp500_pit_monthly.csv"
    USE_PIT_UNIVERSE       = True

    # cstability 4-vote crisis signal (v11 LIVE: crisis-conditional equity gating).
    # Defaults updated 2026-05-04 to v11 LIVE values (crisis_gate_enabled=True,
    # factor=0.25). When 4-vote >= threshold, gross exposure is multiplied by
    # CRISIS_GATE_FACTOR (chained with existing VIX gate). Daily edge-trigger
    # forces an intra-month rebalance on vote crossing — required so fast
    # crashes (e.g. Lehman week) don't wait 2-4 weeks for next month_start to
    # gate equity. PIT 2008-2024: CAGR 23.21% / Sharpe 0.874 / DD -30.5%
    # (vs bare v10 18.63% / 0.65 / -52.1%). Train/holdout opposite-of-overfit
    # passed cleanly. Override via --parameter CRISIS_GATE_ENABLED 0 to revert
    # to bare v10 behavior.
    # 4-vote CSV is the v11 LIVE pin's input (crisis-gate reads vote_count >= 2).
    # 3-vote CSV (--parameter VOTE_STORE_KEY conquest/votes/cstability_3vote_daily.csv)
    # matches what cstability v11.2 LIVE computes internally (INCLUDE_PROB_VOTE=0
    # ablated the SJSU forecast vote — zero marginal value at the cstability
    # level, but at the cgrowth level the 4-vote series fires the crisis-gate
    # 3x more often than the 3-vote series, so cgrowth-standalone reading the
    # 4-vote CSV gives different behavior than CF (which computes votes
    # in-memory via cstability sleeve at v11.2 logic). Keep 4-vote default for
    # LIVE pin reproducibility; pass --parameter VOTE_STORE_KEY ... to test.
    VOTE_STORE_KEY         = "conquest/votes/cstability_4vote_daily.csv"
    CRISIS_GATE_ENABLED    = True   # was False (v10 LIVE) — flipped for v11 LIVE
    CRISIS_GATE_FACTOR     = 0.25   # was 0.50 — 25% strictly Paretos 50% on every metric
    CRISIS_GATE_THRESHOLD  = 2

    # ---------- SIGNAL_MODE: "qm_composite" (v9 LIVE) | "momentum" (v8.6 — pass via --parameter) ----------
    # "qm_composite": rank by z(180d momentum) + z(-60d realized vol). v9 LIVE behavior.
    # "momentum":     rank by 180d momentum only. v8.6 LIVE behavior.
    SIGNAL_MODE            = "qm_composite"

    # ---------- VOL_WEIGHT: composite tilt between momentum and -vol z-scores ----------
    # composite = z(180d momentum) + VOL_WEIGHT * z(-60d realized vol)
    # VOL_WEIGHT = 0.0 → pure momentum (functionally identical to SIGNAL_MODE="momentum" v8.6)
    # VOL_WEIGHT = 1.0 → v9 (equal weighting, superseded)
    # VOL_WEIGHT = 4.0 → v10 LIVE (vol-tilted; promoted 2026-05-03 night, default)
    # VOL_WEIGHT > 4.0 → over-tilted (8.0 sweep showed CAGR collapse to 39.8% — past peak)
    # Cloud Lean sweep 2018-2024 (0.5/1.0/2.0/4.0/6.0/8.0) found 4.0 as the strict-Pareto peak
    # over v9 on every metric: CAGR 46.30→51.62 (+5.32pp), Sharpe 1.338→1.558 (+0.220),
    # DD -31.6%→-25.8% (-5.8pp tighter), Calmar 1.466→2.001 (+0.535), End $359k→$461k (+$102k),
    # PSR 79.4%→92.1% (+12.7pp). Train/holdout (2018-2022 / 2023-2024) also strict-Pareto:
    # train Sharpe 0.97→1.289 (+33%) and DD -31.6%→-24.7%; holdout Sharpe 2.239→2.293 (tied/+).
    # Pass --parameter VOL_WEIGHT 1.0 to revert to v9 behavior for backtests.
    VOL_WEIGHT             = 4.0

    # ---------- WEIGHTING_MODE: "equal" (v8.5) | "rank" (v8.6 LIVE) | "tail_leverage" (v8.7 candidate) ----------
    # "equal":         1/5 each (33%, 33%, 33%, 33%, 33% of equity, normalized) — v8.5 LIVE behavior
    # "rank":          5/15, 4/15, 3/15, 2/15, 1/15 (33%, 27%, 20%, 13%, 7%) — v8.6 LIVE behavior (default)
    # "tail_leverage": 7/15, 4/15, 2/15, 1/15, 1/15 (47%, 27%, 13%, 7%, 7%) — v8.7 candidate
    #     pushes more concentration into rank-1 momentum pick. Trades higher single-stock
    #     concentration risk for higher CAGR potential. Same selection + sector cap + VIX gate.
    # Cloud Lean train/holdout validation (2026-05-03 night, $25k):
    #   Train (2018-2022): Sharpe 1.06 vs v8.5 LIVE 1.023 (+0.037);
    #     CAGR 28.99 vs 26.18 (+2.82pp); DD -36.7 vs -33.1 (-3.6pp wider);
    #     Calmar 0.790 vs 0.791 (tied)
    #   Holdout (2023-2024): Sharpe 1.819 vs v8.5 LIVE 1.807 (+0.012);
    #     CAGR 92.51 vs 83.40 (+9.10pp); DD -24.5 vs -26.5 (+2.0pp tighter);
    #     Calmar 3.776 vs 3.147 (+0.629)
    #   Full period (2018-2024): CAGR 44.78 / Sharpe 1.265 / DD -36.7% /
    #     Calmar 1.220 / End $25k → $334k. +$71k vs v8.5 LIVE end equity.
    # Anti-overfit gate cleared on Sharpe both windows; CAGR robust across
    # both windows (holdout uplift bigger than train, opposite of overfit).
    # DD widens train but tightens holdout — known mandate-acceptable trade.
    # Pass --parameter WEIGHTING_MODE equal to revert to v8.5 LIVE behavior
    # for backtests / parity comparison.
    WEIGHTING_MODE         = "rank"  # v8.6 LIVE: rank-weighted top-5

    # ---------- Quality factor overlay (v11.x candidate, default OFF — LIVE behavior) ----------
    # When QUALITY_FILTER_ENABLED=1, the universe is filtered by per-stock QC
    # Lean Fundamentals BEFORE momentum / Q+M ranking. Stocks must clear:
    #     ROE (TTM)             >= QUALITY_ROE_MIN          (default 10%)
    #     Long-term debt/equity <= QUALITY_DEBT_EQUITY_MAX  (default 1.5)
    #     FCF yield (TTM)       >= QUALITY_FCF_YIELD_MIN    (default 2%)
    # Hypothesis: filter avoids value-trap momentum catches (highly-leveraged
    # or unprofitable names that "moved up" pre-blow-up). Adds defense at the
    # security-selection layer, complementary to the portfolio-level crisis
    # gate. Tested in 2026-05-04 paired backtest and FAILED strict-Pareto
    # hard (CAGR −12.92 pp, end equity −84%) — quality criteria reject the
    # high-momentum mega-cap growth names that drive cgrowth's edge. Kept
    # as gated parameter for future revisits. See LEARNINGS.md for results.
    #
    # Robustness: when fundamentals are unavailable for a security (early
    # 2008 has spotty coverage; non-profile equities miss), the filter
    # DEFAULTS TO PASS (don't reject for missing data). This avoids degenerate
    # "filter rejects everyone" situations in early years.
    QUALITY_FILTER_ENABLED  = 0
    QUALITY_ROE_MIN         = 0.10
    QUALITY_DEBT_EQUITY_MAX = 1.50
    QUALITY_FCF_YIELD_MIN   = 0.02

    def initialize(self):
        # Default: 2018-2024 7yr Lean window. Overridable via --parameter for
        # train/holdout splits (matches cgrowth_options pattern). Adding these
        # parameter hooks does not change LIVE behavior when no override is supplied.
        start_year = int(self.get_parameter("BACKTEST_START_YEAR") or 2018)
        end_year   = int(self.get_parameter("BACKTEST_END_YEAR")   or 2024)
        self.set_start_date(start_year, 1, 1)
        self.set_end_date(end_year, 12, 31)
        self.set_cash(25000)
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE)
        self.set_benchmark("SPY")

        # Slippage model — IB-realistic VolumeShareSlippageModel.
        slip_mode = (self.get_parameter("SLIPPAGE_MODEL") or "volume_share").lower()
        if slip_mode == "volume_share":
            def _init_security(security):
                try: security.set_slippage_model(VolumeShareSlippageModel(0.025, 0.1))
                except Exception: pass
            self.set_security_initializer(_init_security)
            self.log("[cgrowth] slippage: VolumeShareSlippageModel(0.025, 0.1)")
        elif slip_mode != "none":
            self.log(f"[cgrowth] slippage: NONE (Lean default)")

        # WEIGHTING_MODE override. Default "rank" preserves v8.6/v9 LIVE behavior.
        # Modes: "equal" (v8.5), "rank" (v8.6/v9 LIVE), "tail_leverage" (v8.7 — REJECTED).
        wm = self.get_parameter("WEIGHTING_MODE")
        if wm in ("equal", "rank", "tail_leverage"):
            self.WEIGHTING_MODE = wm

        # SIGNAL_MODE override. Default "qm_composite" = v9 LIVE behavior.
        # Modes: "qm_composite" (v9 LIVE), "momentum" (v8.6 LIVE — pure 180d MOMP).
        sm = self.get_parameter("SIGNAL_MODE")
        if sm in ("qm_composite", "momentum"):
            self.SIGNAL_MODE = sm

        # VOL_WEIGHT override. Default 4.0 = v10 LIVE composite weighting.
        # Only effective when SIGNAL_MODE == "qm_composite".
        vw = self.get_parameter("VOL_WEIGHT")
        if vw is not None and vw != "":
            try:
                self.VOL_WEIGHT = float(vw)
            except ValueError:
                pass

        # SAFE_TICKER override — defensive holding when no positive-momentum stock.
        # Default "IEF" (7-10yr Treasury) preserves v9/v11 LIVE behavior.
        # Test alternatives: "TMF" (3x 20yr Treasury — amplified flight-to-quality)
        # or "BIL" (1mo T-bill — pure cash). Use --parameter SAFE_TICKER TMF.
        st = self.get_parameter("SAFE_TICKER")
        if st and st.strip():
            self.SAFE_TICKER = st.strip().upper()

        # USE_PIT_UNIVERSE override — use 2008-2024 union universe + monthly PIT
        # snapshots to filter the active set at each rebalance. Eliminates
        # lookahead bias for extended-history backtests. Default ON (matches
        # v11 LIVE pin); pass --parameter USE_PIT_UNIVERSE 0 to revert to the
        # static-universe v10 LIVE comparison behavior.
        upu = self.get_parameter("USE_PIT_UNIVERSE")
        if upu is not None and upu != "":
            try:
                self.USE_PIT_UNIVERSE = bool(int(upu))
            except ValueError:
                pass

        # QUALITY filter overrides (default OFF preserves v11 LIVE behavior).
        # Activate via --parameter QUALITY_FILTER_ENABLED 1.
        qfe = self.get_parameter("QUALITY_FILTER_ENABLED")
        if qfe and int(qfe):
            self.QUALITY_FILTER_ENABLED = 1
        for attr, key, cast in [
            ("QUALITY_ROE_MIN",         "QUALITY_ROE_MIN",         float),
            ("QUALITY_DEBT_EQUITY_MAX", "QUALITY_DEBT_EQUITY_MAX", float),
            ("QUALITY_FCF_YIELD_MIN",   "QUALITY_FCF_YIELD_MIN",   float),
        ]:
            v = self.get_parameter(key)
            if v is not None and v != "":
                try:
                    setattr(self, attr, cast(v))
                except ValueError:
                    pass

        # CRISIS_GATE override — sub-fix (c) of GFC drawdown sweep
        cge = self.get_parameter("CRISIS_GATE_ENABLED")
        if cge and int(cge):
            self.CRISIS_GATE_ENABLED = True
        cgf = self.get_parameter("CRISIS_GATE_FACTOR")
        if cgf is not None and cgf != "":
            try:
                self.CRISIS_GATE_FACTOR = float(cgf)
            except ValueError:
                pass
        cgt = self.get_parameter("CRISIS_GATE_THRESHOLD")
        if cgt:
            try:
                self.CRISIS_GATE_THRESHOLD = int(cgt)
            except ValueError:
                pass

        # VOTE_STORE_KEY override — choose 4-vote (v11 LIVE pin input) vs 3-vote
        # (cstability v11.2 LIVE-consistent — drops the ablated SJSU forecast
        # vote). Default 4-vote preserves LIVE pin reproducibility.
        vsk = self.get_parameter("VOTE_STORE_KEY")
        if vsk and vsk.strip():
            self.VOTE_STORE_KEY = vsk.strip()

        # Load universe — PIT mode loads the 801-ticker union; default loads current 503.
        self.pit_monthly = {}
        if self.USE_PIT_UNIVERSE:
            try:
                union_text = self.object_store.read(self.PIT_UNION_KEY)
                pit_text   = self.object_store.read(self.PIT_MONTHLY_KEY)
            except Exception as e:
                raise RuntimeError(f"PIT object-store read failed: {e}. "
                    f"Push storage/conquest/universe/sp500_union_2008_2024.csv and "
                    f"sp500_pit_monthly.csv first.")
            universe_df = pd.read_csv(StringIO(union_text))
            pit_df      = pd.read_csv(StringIO(pit_text))
            for as_of, group in pit_df.groupby("as_of"):
                ym = str(as_of)[:7]  # YYYY-MM key
                self.pit_monthly[ym] = set(group["ticker"].astype(str).tolist())
            self.log(f"PIT universe: union={len(universe_df)} tickers, "
                     f"monthly snapshots={len(self.pit_monthly)} "
                     f"({min(self.pit_monthly)} → {max(self.pit_monthly)})")
        else:
            universe_df = self._load_universe()
            if universe_df is None or universe_df.empty:
                raise RuntimeError(
                    f"No universe at Object Store key {self.UNIVERSE_STORE_KEY}. "
                    "Run scripts/export_sp500_universe.py first."
                )
        self.sector_map = dict(zip(universe_df["ticker"], universe_df["sector"]))
        tickers = universe_df["ticker"].tolist()

        # Add IEF separately (not in S&P 500) as the safe-haven fallback
        self.safe_symbol = self.add_equity(self.SAFE_TICKER, Resolution.DAILY).symbol
        self.symbols_by_ticker: dict = {self.SAFE_TICKER: self.safe_symbol}
        self.signals: dict = {}                  # Symbol -> {"momp"}
        self.symbol_to_ticker: dict = {}         # Symbol -> str (for sector lookup)

        for ticker in tickers:
            equity = self.add_equity(ticker, Resolution.DAILY)
            sym = equity.symbol
            self.symbols_by_ticker[ticker] = sym
            self.symbol_to_ticker[sym] = ticker
            self.signals[sym] = {
                "momp": self.MOMP(sym, self.MOMENTUM_LOOKBACK_DAYS, Resolution.DAILY),
                # v9 quality axis: 60d realized vol (STD of close prices). For
                # ranking, the constant scaling cancels out in z-score.
                "vol":  self.STD(sym, self.VOL_LOOKBACK_DAYS, Resolution.DAILY),
            }
        self.log(f"Universe loaded: {len(self.signals)} S&P 500 stocks + IEF safe-haven.")

        self.set_warm_up(self.WARMUP_BARS, Resolution.DAILY)

        # Production hardening — shared across all Conquest projects.
        try:
            from conquest.production import harden
            harden(self)
        except Exception as e:
            self.log(f"[cgrowth] production hardening skipped: {e}")

        self.schedule.on(
            self.date_rules.month_start("SPY"),
            self.time_rules.after_market_open("SPY", 30),
            self.rebalance,
        )
        # Daily VIX gate update (carries between monthly rebalances)
        self.schedule.on(
            self.date_rules.every_day("SPY"),
            self.time_rules.after_market_open("SPY", 5),
            self._update_risk_off,
        )

        self.vix_df = self._load_vix()
        self.risk_off = False

        # Crisis-gate vote signal (sub-fix c). Loaded only when CRISIS_GATE_ENABLED.
        self.vote_df = self._load_vote_signal() if self.CRISIS_GATE_ENABLED else None
        self.last_vote_was_above_threshold = False

    # ---------- Object Store loaders ----------

    def _load_universe(self):
        try:
            csv_text = self.object_store.read(self.UNIVERSE_STORE_KEY)
        except Exception as e:
            self.error(f"Object Store read of {self.UNIVERSE_STORE_KEY} failed: {e}")
            return None
        if not csv_text:
            return None
        try:
            return pd.read_csv(StringIO(csv_text))
        except Exception as e:
            self.error(f"Failed to parse universe CSV: {e}")
            return None

    def _load_vix(self):
        try:
            csv_text = self.object_store.read(self.VIX_STORE_KEY)
        except Exception as e:
            self.error(f"Object Store read of {self.VIX_STORE_KEY} failed: {e}")
            return None
        if not csv_text:
            return None
        try:
            df = pd.read_csv(StringIO(csv_text), index_col=0, parse_dates=True)
            self.log(
                f"VIX feed: {len(df)} rows, range "
                f"{df.index[0].date()} → {df.index[-1].date()}, "
                f"last value = {float(df.iloc[-1, 0]):.2f}"
            )
            return df
        except Exception as e:
            self.error(f"Failed to parse VIX CSV: {e}")
            return None

    def _load_vote_signal(self):
        """Load cstability 4-vote daily signal (pre-computed by scripts/compute_4vote_signal.py)."""
        try:
            csv_text = self.object_store.read(self.VOTE_STORE_KEY)
        except Exception as e:
            self.error(f"Object Store read of {self.VOTE_STORE_KEY} failed: {e}")
            return None
        if not csv_text:
            self.log(f"WARN: {self.VOTE_STORE_KEY} not in Object Store; crisis gate inert.")
            return None
        try:
            df = pd.read_csv(StringIO(csv_text), index_col=0, parse_dates=True)
            self.log(f"vote signal: {len(df)} rows, {df.index[0].date()} -> {df.index[-1].date()}")
            return df
        except Exception as e:
            self.error(f"Failed to parse vote signal CSV: {e}")
            return None

    def _current_vote(self) -> int:
        """At-or-before lookup matching cstability/main.py:307-316 _latest_value()."""
        if self.vote_df is None:
            return 0
        valid = self.vote_df.index <= self.time
        if not valid.any():
            return 0
        return int(self.vote_df.loc[valid, "vote_count"].iloc[-1])

    # ---------- VIX gate ----------

    def _current_vix(self):
        if self.vix_df is None:
            return None
        valid = self.vix_df.index <= self.time
        if not valid.any():
            return None
        return float(self.vix_df.loc[valid].iloc[-1, 0])

    def _update_risk_off(self):
        vix = self._current_vix()
        if vix is not None:
            if not self.risk_off and vix > self.VIX_HIGH:
                self.risk_off = True
                self.log(f"{self.time:%Y-%m-%d}: VIX={vix:.1f} > {self.VIX_HIGH}, entering risk-off")
            elif self.risk_off and vix < self.VIX_LOW:
                self.risk_off = False
                self.log(f"{self.time:%Y-%m-%d}: VIX={vix:.1f} < {self.VIX_LOW}, exiting risk-off")

        # Crisis-gate edge trigger (sub-fix c). Forces an intra-month rebalance
        # on vote_count crossing the threshold so fast crashes (e.g. Lehman week)
        # don't wait 2-4 weeks for next month_start to gate equity exposure.
        if self.CRISIS_GATE_ENABLED:
            vote_above = self._current_vote() >= self.CRISIS_GATE_THRESHOLD
            if vote_above != self.last_vote_was_above_threshold:
                self.log(
                    f"{self.time:%Y-%m-%d}: crisis-gate edge "
                    f"{self.last_vote_was_above_threshold}->{vote_above} "
                    f"(vote_count={self._current_vote()}); intra-month rebalance"
                )
                self.last_vote_was_above_threshold = vote_above
                self.rebalance()

    # ---------- selection + sizing ----------

    def _apply_sector_cap(self, weights: dict) -> dict:
        """Cap per-sector total weight at MAX_PER_SECTOR; freed weight NOT redistributed.

        Args:
            weights: dict[Symbol, float] with current target weights.
        Returns:
            dict[Symbol, float] with sector-capped weights.
        """
        # Aggregate by sector
        sector_totals: dict[str, float] = {}
        sector_symbols: dict[str, list] = {}
        for sym, w in weights.items():
            ticker = self.symbol_to_ticker.get(sym)
            sector = self.sector_map.get(ticker, "Unknown") if ticker else "Unknown"
            sector_totals[sector] = sector_totals.get(sector, 0.0) + abs(w)
            sector_symbols.setdefault(sector, []).append(sym)

        # Scale down over-cap sectors
        out = dict(weights)
        for sector, total in sector_totals.items():
            if total > self.MAX_PER_SECTOR:
                scale = self.MAX_PER_SECTOR / total
                for sym in sector_symbols[sector]:
                    out[sym] = weights[sym] * scale
        return out

    def _passes_quality_filter(self, sym) -> bool:
        """Quality factor gate via QC Lean Fundamentals. Returns True (pass) when
        QUALITY_FILTER_ENABLED=0 (LIVE behavior) OR when fundamentals data is
        unavailable for the security (avoid degenerate "filter rejects everyone"
        in early-history windows).

        When enabled and data IS available, fires only on stocks that clear:
            ROE (TTM)             >= QUALITY_ROE_MIN
            Long-term debt/equity <= QUALITY_DEBT_EQUITY_MAX
            FCF / market_cap      >= QUALITY_FCF_YIELD_MIN
        """
        if not self.QUALITY_FILTER_ENABLED:
            return True
        sec = self.securities.get(sym) if hasattr(self.securities, "get") else None
        if sec is None:
            sec = self.securities[sym] if sym in self.securities else None
        if sec is None:
            return True
        fund = getattr(sec, "fundamentals", None)
        if fund is None or not getattr(fund, "has_fundamental_data", False):
            return True
        try:
            roe = float(fund.operation_ratios.return_on_equity.three_months)
        except (AttributeError, TypeError, ValueError):
            roe = None
        try:
            de = float(fund.operation_ratios.long_term_debt_equity_ratio.three_months)
        except (AttributeError, TypeError, ValueError):
            de = None
        try:
            fcf = float(fund.financial_statements.cash_flow_statement.free_cash_flow.twelve_months)
            market_cap = float(getattr(fund, "market_cap", 0)) or float(getattr(sec, "price", 0)) * float(getattr(fund, "shares_outstanding", 0))
            fcf_yield = (fcf / market_cap) if market_cap > 0 else None
        except (AttributeError, TypeError, ValueError, ZeroDivisionError):
            fcf_yield = None
        # Default-pass on missing inputs (don't reject a stock for missing data).
        if roe is not None and roe < self.QUALITY_ROE_MIN:
            return False
        if de is not None and de > self.QUALITY_DEBT_EQUITY_MAX:
            return False
        if fcf_yield is not None and fcf_yield < self.QUALITY_FCF_YIELD_MIN:
            return False
        return True

    def _select_momentum_only(self) -> list:
        """v8.6 LIVE selection: top-N by 180d momentum, positive-momentum filter."""
        pit_active = self._pit_active_set()
        scored = []
        for sym in self.signals:
            if pit_active is not None:
                ticker = self.symbol_to_ticker.get(sym)
                if ticker not in pit_active:
                    continue
            if not self.signals[sym]["momp"].is_ready:
                continue
            if not self._passes_quality_filter(sym):
                continue
            scored.append((sym, float(self.signals[sym]["momp"].current.value)))
        eligible = [(sym, m) for sym, m in scored if m > 0]
        eligible.sort(key=lambda p: p[1], reverse=True)
        return [sym for sym, _ in eligible[: self.TOP_N]]

    def _pit_active_set(self):
        """Return set of tickers in the S&P 500 for the current rebalance month.
        Returns None if PIT mode is off (no filter applied)."""
        if not self.USE_PIT_UNIVERSE or not self.pit_monthly:
            return None
        ym = self.time.strftime("%Y-%m")
        if ym in self.pit_monthly:
            return self.pit_monthly[ym]
        # Fall back to most recent snapshot at or before current month
        candidates = [m for m in self.pit_monthly if m <= ym]
        if not candidates:
            return set()
        return self.pit_monthly[max(candidates)]

    def _select_qm_composite(self) -> list:
        """v9/v10 selection: top-N by Q+M composite (z(180d momentum) + VOL_WEIGHT × z(-60d vol))."""
        pit_active = self._pit_active_set()
        eligible = []
        for sym, sigs in self.signals.items():
            # PIT membership filter (no-op when not in PIT mode)
            if pit_active is not None:
                ticker = self.symbol_to_ticker.get(sym)
                if ticker not in pit_active:
                    continue
            momp_ind = sigs["momp"]
            vol_ind = sigs["vol"]
            if not momp_ind.is_ready or not vol_ind.is_ready:
                continue
            mom_value = float(momp_ind.current.value)
            vol_value = float(vol_ind.current.value)
            if mom_value <= 0 or vol_value <= 0:
                continue
            if not self._passes_quality_filter(sym):
                continue
            eligible.append((sym, mom_value, vol_value))
        if not eligible:
            return []
        moms = [m for _, m, _ in eligible]
        vols = [v for _, _, v in eligible]
        n = len(eligible)
        mom_mean = sum(moms) / n
        vol_mean = sum(vols) / n
        mom_std = (sum((m - mom_mean) ** 2 for m in moms) / n) ** 0.5 or 1.0
        vol_std = (sum((v - vol_mean) ** 2 for v in vols) / n) ** 0.5 or 1.0
        scored = []
        for sym, mom_value, vol_value in eligible:
            z_mom = (mom_value - mom_mean) / mom_std
            z_qual = -((vol_value - vol_mean) / vol_std)
            composite = z_mom + self.VOL_WEIGHT * z_qual
            scored.append((sym, composite))
        scored.sort(key=lambda p: p[1], reverse=True)
        return [sym for sym, _ in scored[: self.TOP_N]]

    def rebalance(self) -> None:
        if self.is_warming_up:
            return

        # Selection: v8.6 momentum-only OR v9 Q+M composite per SIGNAL_MODE.
        # Both filter to positive 180d momentum first (Antonacci dual-momentum).
        if self.SIGNAL_MODE == "qm_composite":
            chosen = self._select_qm_composite()
        else:
            chosen = self._select_momentum_only()

        # Liquidate anything not in chosen, except IEF (handled below)
        for sym in self.signals:
            if sym not in chosen and self.portfolio[sym].invested:
                self.liquidate(sym)

        if not chosen:
            self.log(
                f"{self.time:%Y-%m-%d}: no S&P 500 stock has positive 180d momentum; "
                f"parking 100% in {self.SAFE_TICKER}."
            )
            self.set_holdings(self.safe_symbol, 1.0)
            return

        # Exit IEF if we were parked there
        if self.portfolio[self.safe_symbol].invested:
            self.liquidate(self.safe_symbol)

        # Initial allocation per WEIGHTING_MODE
        n = len(chosen)
        if self.WEIGHTING_MODE == "tail_leverage" and n >= 2:
            # Tail-leveraged weights: rank-1 gets the lion's share. For TOP_N=5: [7/15, 4/15, 2/15, 1/15, 1/15].
            # Generalizes via geometric-decreasing pattern with cap at min weight 1/denom.
            # Hard-coded 5-name table (matches v8.7 candidate spec); falls back to rank-weight
            # for other TOP_N values.
            if n == 5:
                raw = [7.0, 4.0, 2.0, 1.0, 1.0]
            elif n == 4:
                raw = [6.0, 3.0, 2.0, 1.0]
            elif n == 3:
                raw = [5.0, 3.0, 2.0]
            elif n == 2:
                raw = [3.0, 2.0]
            else:
                # Single name: full weight
                raw = [1.0]
            denom = sum(raw)
            weights = {sym: raw[i] / denom for i, sym in enumerate(chosen)}
        elif self.WEIGHTING_MODE == "rank":
            # Rank weights: 5/15, 4/15, 3/15, 2/15, 1/15 (v8.6 LIVE)
            denom = n * (n + 1) / 2.0
            weights = {sym: (n - i) / denom for i, sym in enumerate(chosen)}
        else:
            # Equal weights (v8.5 LIVE behavior)
            equal_weight = 1.0 / n
            weights = {sym: equal_weight for sym in chosen}
        weights = self._apply_sector_cap(weights)

        # VIX gate: scale gross by 0.5 if risk_off
        scale = self.RISK_OFF_FACTOR if self.risk_off else 1.0

        # Crisis gate (sub-fix c): chain crisis_scale on top of VIX gate when vote fires.
        crisis_active = False
        if self.CRISIS_GATE_ENABLED and self._current_vote() >= self.CRISIS_GATE_THRESHOLD:
            scale *= self.CRISIS_GATE_FACTOR
            crisis_active = True

        for sym, w in weights.items():
            self.set_holdings(sym, w * scale)

        vix_now = self._current_vix()
        vix_str = f"{vix_now:.1f}" if vix_now is not None else "n/a"
        chosen_tickers = [self.symbol_to_ticker.get(s, str(s)) for s in chosen]
        gross = sum(weights.values()) * scale
        self.log(
            f"{self.time:%Y-%m-%d}: weighting={self.WEIGHTING_MODE} VIX={vix_str} "
            f"risk_off={self.risk_off} crisis={crisis_active} (vote={self._current_vote()}) "
            f"scale={scale:.2f} gross={gross:.2%} "
            f"top {len(chosen)} stocks: {chosen_tickers[:8]}{'...' if len(chosen_tickers) > 8 else ''}"
        )

    def on_data(self, data: Slice) -> None:
        # Phase 4 will hook options entry/exit triggers here.
        pass
